### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DominiqueMakowski** [mad-lab-fau/BioPsyKit#1]
Hi @richrobe, hope you're doing great ☺️ 
I just stumbled across this nice package, and there are some very useful and interesting stuff here, looking forward to see its future development! 

And looking at the ECG code, there are actually several interesting features that we don't have in neurokit afaik, such as some outliers detection methods or one of the EDR method computation, etc (pinging @zen-juen to double-check). I was wondering if you would be okay if we added them in NK too as it could also benefit our users? It could potentially decrease the complexity / length of your code if you wanted then to call these functions from there (I'm saying that coz I saw you already have NK as a dependency) Anyway, let me know what you think! Take care

**Comment by richrobe** [comment]
Hi @DominiqueMakowski!

I'm very sorry – I totally forgot to reply to your issue. Yes sure, happy to merge parts of my code into Neurokit (and also happy to collaborate in general if you're interested). Let me know how I can help you with that?

Best,
Robert

**Comment by zen-juen** [comment]
Hi @richrobe, after taking a look at the source code, I found the EDR methods quite interesting (especially since edr methods are currently quite underdeveloped in nk) and believe they will benefit the wider audience (including the nk community). Just wondering for the `peak_trough_mean`, `peak_trough_diff` and `peak_peak_interval` methods, do you have references for them? 😄
