### ISSUE TITLE
WearDetection - algorithm reference

### ISSUE THREAD

**Issue by FilippoCMC** [mad-lab-fau/BioPsyKit#43]
Thanks very much for putting together this lovely package :-) I was wondering if you could point me towards the reference/publication for the no-wear detection algorithm implemented in the class `WearDetection` [here](https://github.com/mad-lab-fau/BioPsyKit/blob/cee8d91e6f8d9f40e6df75746562ea3715873dcd/src/biopsykit/signals/imu/wear_detection.py#L12). Furthermore, why did you choose that particular algorithm, if I may ask? Thanks!

**Comment by richrobe** [comment]
Hi, thanks! :-)

Sure, the wear detection algorithm was implemented according to [this](https://doi.org/10.1371/journal.pone.0022922) paper, with modifications according to [this](https://doi.org/doi.org/10.1371/journal.pone.0061691) paper. We those this particular algorithm because it's also used in the [GGIR](https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html) R package, which is quite well-established for IMU processing in sleep and physical activity reserach.

I also added the two references to the class documentation!
